# VPS <-> blog-vm
[server]
bind_addr = "0.0.0.0:42070"
heartbeat_interval = 60

[server.transport]
type = "noise"

[server.transport.tcp]
nodelay = true
keepalive_secs = 30
keepalive_interval = 8

[server.transport.noise]
pattern = "Noise_NK_25519_ChaChaPoly_BLAKE2s"
local_private_key = "redacted"
remote_public_key = "redacted"

[server.services.nginx]
bind_addr = "0.0.0.0:3100"
token = "redacted"