# VPS <-> containers-vm
[server]
# This is a TCP port btw, wish you could do UDP like in frps but meh...
bind_addr = "0.0.0.0:42069"
heartbeat_interval = 60

[server.transport]
type = "noise"

[server.transport.tcp]
nodelay = true
keepalive_secs = 30
keepalive_interval = 8

[server.transport.noise]
pattern = "Noise_NK_25519_ChaChaPoly_BLAKE2s"
local_private_key = "redacted"
remote_public_key = "redacted"

# nodelay = true is on by default
[server.services.whoogle]
type = "tcp"
token = "redacted"
# local binding
bind_addr = "0.0.0.0:3000"

[server.services.rimgo]
type = "tcp"
token = "redacted
bind_addr = "0.0.0.0:3001"

[server.services.umami]
type = "tcp"
token = "redacted"
bind_addr = "0.0.0.0:3002"

[server.services.zipline]
type = "tcp"
token = "redacted"
bind_addr = "0.0.0.0:3003"

[server.services.upload]
type = "tcp"
token = "redacted"
bind_addr = "0.0.0.0:3004"