# Podman 4.3.1, podman-compose devel branch
services:
  postgres:
    image: docker.io/library/postgres:15.3-alpine3.18
    container_name: postgresql
    env_file:
      - postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  statping-ng:
    image: docker.io/adamboutcher/statping-ng:v0.90.78
    container_name: statping-ng
    NetworkHandler: slirp4netns
    # For whatever reason, env_file doesn't work for this
    environment:
      # Database envs
      - DB_DSN=postgres
      - DB_CONN=postgres
      - DB_HOST=postgres
      - DB_USER=<redacted>
      - DB_PASS=<redacted>
      - DB_DATABASE=pingdb
      - POSTGRES_SSLMODE=disable
      # Stat ping envs
      - VERBOSE=1
      - DISABLE_LOGS=false
      - ALLOW_REPORTS=true
      # Automatic setup envs
      - NAME=Uptime Overseer
      - DESCRIPTION=Live, Laugh, Monitor
      - DOMAIN=https://uptime.rubberverse.xyz
      - ADMIN_USER=<redacted>
      - ADMIN_PASSWORD=<redacted>
      - ADMIN_EMAIL=<redacted>
      - SAMPLE_DATA=false
      # Connection
      - BASE_PATH=monitor
      - LANGUAGE=en
    volumes:
    # Needed to get themes to work since it fails to download index.scss
      - ${HOME}/statping:/app 
    ports:
      - '127.0.0.1:3200:8080'
    labels:
      - io.containers.autoupdate=registry
    depends_on:
      - postgres
volumes:
  postgres-data: